project:
  type: book
  output-dir: docs

book:
  title: "Computational Social Science Cookbook with R"
  author: "Wei Wang, Mete Akcaoglu, Joshua Rosenberg, Shaun Kellogg"
  date: " January 11,2025"
  chapters:
    - index.qmd
    - section-1.qmd
    - section-2.qmd
    - section-3.qmd
    - section-4.qmd
    - section-5.qmd
    - section-6.qmd
    - conclusion.qmd
    - references.qmd

bibliography: [references.bib, packages.bib]

format:
  html:
    theme: flatly
    number-sections: false   # Turn off HTML autonumbering
  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    number-sections: false   # Turn off PDF autonumbering

editor: visual

execute:
  warning: false